name: Jekyll Themes
baseurl: /blogtheme
description: Insert tagline here

permalink: /themes/:title/

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
